const repo = 'https://github.com/samuelcorsan/better-government';

export const links = {
  repo,
  install: `${repo}#desarrollo`,
  architecture: `${repo}/blob/main/docs/ARCHITECTURE.md`,
  design: `${repo}/blob/main/DESIGN.md`,
  contributing: `${repo}/blob/main/CONTRIBUTING.md`,
  security: `${repo}/blob/main/SECURITY.md`,
  license: `${repo}/blob/main/LICENSE`,
  extranjeria: `${repo}/tree/main/sites/extranjeria`,
  dni: `${repo}/tree/main/sites/dni`,
};

export const nav = [
  { href: '#texto', label: 'El texto' },
  { href: '#horizonte', label: 'Hoja de ruta' },
  { href: '#preguntas', label: 'Preguntas' },
];

/** Provincias tal y como las ofrece la web oficial (fixture del 27/09/2026). */
export const provincias = [
  'A Coruña',
  'Albacete',
  'Alicante',
  'Almería',
  'Araba',
  'Asturias',
  'Ávila',
  'Badajoz',
  'Barcelona',
  'Bizkaia',
  'Burgos',
  'Cáceres',
  'Cádiz',
  'Cantabria',
  'Castellón',
  'Ceuta',
  'Ciudad Real',
  'Córdoba',
  'Cuenca',
  'Gipuzkoa',
  'Girona',
  'Granada',
  'Guadalajara',
  'Huelva',
  'Huesca',
  'Illes Balears',
  'Jaén',
  'La Rioja',
  'Las Palmas',
  'León',
  'Lleida',
  'Lugo',
  'Madrid',
  'Málaga',
  'Melilla',
  'Murcia',
  'Navarra',
  'Ourense',
  'Palencia',
  'Pontevedra',
  'Salamanca',
  'S.Cruz Tenerife',
  'Segovia',
  'Sevilla',
  'Soria',
  'Tarragona',
  'Teruel',
  'Toledo',
  'Valencia',
  'Valladolid',
  'Zamora',
  'Zaragoza',
];

export const pasos = [
  'Información del trámite',
  'Provincia',
  'Oficina y trámite',
  'Requisitos y forma de acceso',
  'Tus datos y la cita',
];
